apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-k8s
  namespace: postgres
  labels:
    app.kubernetes.io/name: postgres-exporter-k8s
    app.kubernetes.io/part-of: observability
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres-exporter-k8s
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
