apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter-k8s
  namespace: observability
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/part-of: observability
spec:
  namespaceSelector:
    matchNames:
      - postgres
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-exporter-k8s
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
      path: /metrics
