apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-portal
  namespace: observability
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/name: api-portal
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - api-portal
  selector:
    matchLabels:
      app.kubernetes.io/name: api-portal
      app.kubernetes.io/component: portal
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
      path: /metrics
